# Generated by Django 5.0.4 on 2024-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0004_alter_usernotes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usernotes',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
