# Generated by Django 5.0.4 on 2024-04-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notesapp', '0003_usernotes_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotes',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
